### ISSUE TITLE
 Volume mount fails if file with special characters in filename exists in target folder

### ISSUE THREAD

**Issue by gribok** [nestybox/sysbox#629]
This issue looks similar as #515 

I have a file with special characters in the filename in my Docker bind volume

On my filesystem, the filename is showed as `K?ln_SOLL.xlsx`.
`stat` command shows me the correct filename: `K\366ln_SOLL.xlsx`

The container creation fails as in #515 with
```
Error response from daemon: failed to copy xattrs: failed to list xattrs on /var/lib/docker/overlay2/c26516400183a8d6840c8c4c31a97883d6c282ee1e62381f00de6ec944296029/merged/data/www/uploads/K�ln_SOLL.xlsx: no such file or directory
```

After removing this file, the volume mounting works in SYSBOX.

**Comment by ctalledo** [comment]
Hi @gribok, thanks for using Sysbox and for reporting the issue.

```
Error response from daemon: failed to copy xattrs: failed to list xattrs on /var/lib/docker/overlay2/c26516400183a8d6840c8c4c31a97883d6c282ee1e62381f00de6ec944296029/merged/data/www/uploads/K�ln_SOLL.xlsx: no such file or directory
```

That error is actually coming from Docker / containerd, not from Sysbox (i.e., you should see the same behavior when running a container with Docker without Sysbox). 

If possible, please file the issue on the [containerd repo](https://github.com/containerd/containerd).

Closing it here; please re-open if you think otherwise. Thanks again.
