### ISSUE TITLE
Unable to get sysbox-in-docker running

### ISSUE THREAD

**Issue by networkException** [nestybox/sysbox#632]
Hello! I've been trying to get sysbox-in-docker running but get

`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: container_linux.go:425: starting container process caused: process_linux.go:607: container init caused: process_linux.go:528: applying cgroup configuration for process caused: failed to write 525 to cgroup.procs: write /sys/fs/cgroup/docker/018626e18391939969f1d903ea02348d0d80f03fb0006e4de926e0c14fda9ef8/init.scope/cgroup.procs: operation not supported: unknown.`

when running `docker run --runtime=sysbox-runc hello-world` inside the privileged container (started with `docker run --privileged --rm --hostname sysbox-in-docker --name sysbox-in-docker -v /root/sysbox-testing/sysbox-var-lib-docker:/var/lib/docker -v /root/sysbox-testing/sysbox-var-lib-sysbox:/var/lib/sysbox -v /lib/modules/5.15.0-58-generic:/lib/modules/5.15.0-58-generic:ro -v /usr/src/linux-headers-5.15.0-58-generic:/usr/src/linux-headers-5.15.0-58-generic:ro -v /usr/src/linux-headers-5.15.0-58:/usr/src/linux-headers-5.15.0-58:ro <image>`)

The build setup I used can be found at https://github.com/networkException/sysbox-in-docker. Note that the actual instructions to build sysbox binaries is a mix of installing dependencies the build process complained about were required, patching a few files as shown in the travis CI config and running `make sysbox-local`. The second stage (the image that gets run with the command above) is pretty much an exact copy of the [sysbox-in-docker focal](https://github.com/nestybox/sysbox/blob/master/sysbox-in-docker/Dockerfile.ubuntu-focal) image (but using `ubuntu:jammy`).

Based on other issues I thought this might be related to shiftfs (and I think a previous error was), so I disabled it [here](https://github.com/networkException/sysbox-in-docker/blob/master/s6-services/sysbox-mgr/run).

Any help getting this to run is greatly appreciated!

**Comment by ctalledo** [comment]
Hi @networkException, thanks for trying Sysbox (and in this case sysbox-in-docker).

To be honest, it's been a while since we've run the sysbox-in-docker container (and we don't regularly test it), so I am not surprised it's giving trouble. It was meant as a way to help users quickly try Sysbox without installing it on their hosts, but not many people use it. As a result it's not been properly maintained.

However, for testing Sysbox locally and in CI, we do run Sysbox inside a privileged docker container and it works great. So while the sysbox-in-docker directory is outdated right now, it's definitely possible to run Sysbox inside a privileged container. 

We don't have the cycles to update the sysbox-in-docker container right now, but here are some pointers on the privileged test container, which as I mentioned we regularly use. On a Ubuntu host (preferably one where shiftfs is installed and works):

1) Clone the sysbox repo (`git clone --recurse-submodules git@github.com:nestybox/sysbox.git`)
2) Run `make test-shell`

That will launch a privileged container, inside of which docker + sysbox are running.

The privileged container images are in the `./tests` subdir. The "./Makefile" starts the test container (see the `test-shell`) make target. The `./tests/scr/testContainerPre` and `./tests/scr/testContainerInit` scripts start docker and sysbox inside the test container. 

Hope that helps!

**Comment by networkException** [comment]
Hey! Thanks for the pointers, I was able to get it running successfully with by running https://github.com/nestybox/sysbox/blob/master/tests/scr/testContainerCgv2Fix in the container on startup (it seems to work even without the endless loop)

Thanks for the great project!
