### ISSUE TITLE
Uninstall didn't work

### ISSUE THREAD

**Issue by dimm0** [nestybox/sysbox#688]
Trying to uninstall the sysbox.

Had the logs in the uninstall pod:

```
E0502 19:26:40.723068      26 memcache.go:238] couldn't get current server API group list: Get "https://10.96.0.1:443/api?timeout=32s": dial tcp 10.96.0.1:443: connect: network is unreachable
E0502 19:26:40.723309      26 memcache.go:238] couldn't get current server API group list: Get "https://10.96.0.1:443/api?timeout=32s": dial tcp 10.96.0.1:443: connect: network is unreachable
E0502 19:26:40.724962      26 memcache.go:238] couldn't get current server API group list: Get "https://10.96.0.1:443/api?timeout=32s": dial tcp 10.96.0.1:443: connect: network is unreachable
E0502 19:26:40.726579      26 memcache.go:238] couldn't get current server API group list: Get "https://10.96.0.1:443/api?timeout=32s": dial tcp 10.96.0.1:443: connect: network is unreachable
E0502 19:26:40.727880      26 memcache.go:238] couldn't get current server API group list: Get "https://10.96.0.1:443/api?timeout=32s": dial tcp 10.96.0.1:443: connect: network is unreachable
Unable to connect to the server: dial tcp 10.96.0.1:443: connect: network is unreachable
ERROR: Sysbox is not supported on this Kubernetes version ().
Stream closed EOF for kube-system/sysbox-cleanup-k8s-fz8px (sysbox-cleanup-k8s)
```

Also manually running the .sh script on the node produced this:

```
+ grep kubelet_env_file /var/lib/sysbox-deploy-k8s/config
+ echo 'Failed to revert kubelet config; config not found in /var/lib/sysbox-deploy-k8s/config'
Failed to revert kubelet config; config not found in /var/lib/sysbox-deploy-k8s/config
+ return
+ restart_kubelet
+ echo 'Restarting Kubelet ...'
```

There's no `kubelet_env_file` in the config.

Calico CNI, k8s 1.23 (kubeadm baremetal)

**Comment by dimm0** [comment]
Reinstalling also is broken now. Is there a description of manual steps to clean this?

**Comment by ctalledo** [comment]
Hi @dimm0, sorry to hear you having problems with the uninstallation. We test both the installation and uninstallation, so the error you are seeing is unexpected.

Question: did the installation succeed? I ask because the log above shows:

```
ERROR: Sysbox is not supported on this Kubernetes version ().
```

FYI, the installation / uninstallation script is designed to run inside a sysbox-deploy pod; it won't run at host level. 

>  Is there a description of manual steps to clean this?

We don't have a description of the manual steps to install or uninstall unfortunately. It's a bit of a complicated process as the uninstallation must undo the installation steps (e.g. ,configure the kubelet to use containerd instead of CRI-O, remove CRI-O, remove Sysbox, and remove the Sysbox runtime class from K8s).

How can we help further?

**Comment by dimm0** [comment]
Thanks, I'll try to reinstall manually with CRI-O. That seems to be less invasive process.
