### ISSUE TITLE
Is shiftfs still a requirement?

### ISSUE THREAD

**Issue by shadjiiski** [nestybox/sysbox#700]
I am evaluating the option to use sysbox on [PhotonOS](https://vmware.github.io/photon/) and so far I was able to spin it on photon 5.0 GA with and without shiftfs (built manually). According to my sysbox-mgr logs, ID-mapped mounts on overlay FS are working fine:
```
time="2023-05-17 10:00:45" level=info msg="Starting ..."
time="2023-05-17 10:00:45" level=info msg="Sysbox data root: /var/lib/sysbox"
time="2023-05-17 10:00:47" level=debug msg="Running shiftfs check on host."
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: found shiftfs module."
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: test dir = /var/lib/sysbox/sysbox-shiftfs-check3349508767/test (ext4)"
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: marked shiftfs on /var/lib/sysbox/sysbox-shiftfs-check3349508767/test"
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: spawning child process (1473) into user-ns"
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: passed"
time="2023-05-17 10:00:47" level=debug msg="Running shiftfs-on-overlayfs check on host."
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: found shiftfs module."
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: test dir = /var/lib/sysbox/sysbox-shiftfs-check3627236410/test (ext4)"
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: mounted overlayfs on /var/lib/sysbox/sysbox-shiftfs-check3627236410/test"
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: marked shiftfs on /var/lib/sysbox/sysbox-shiftfs-check3627236410/test"
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: spawning child process (1475) into user-ns"
time="2023-05-17 10:00:47" level=debug msg="- shiftfs check: passed"
time="2023-05-17 10:00:47" level=info msg="Shiftfs module found in kernel: yes"
time="2023-05-17 10:00:47" level=info msg="Shiftfs works properly: yes"
time="2023-05-17 10:00:47" level=info msg="Shiftfs-on-overlayfs works properly: yes"
time="2023-05-17 10:00:47" level=info msg="ID-mapped mounts supported by kernel: yes"
time="2023-05-17 10:00:47" level=info msg="Overlayfs on ID-mapped mounts supported by kernel: yes"
time="2023-05-17 10:00:47" level=info msg="Operating in system container mode."
time="2023-05-17 10:00:47" level=info msg="Inner container image preloading enabled."
time="2023-05-17 10:00:47" level=info msg="Listening on /run/sysbox/sysmgr.sock"
time="2023-05-17 10:00:47" level=info msg="Ready ..."
```

The [design readme](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/design.md?plain=1#L109-L115) suggests that shiftfs is redundant for kernel >= 5.19 while the [install-package readme](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-package.md?plain=1#L204-L206) still recommends to install it on kernel > 5.12. I have also found [this issue](https://github.com/nestybox/sysbox/issues/596#issuecomment-1437883902) which suggests shiftfs will be redundant in sysbox 0.6.0+.

Let's clear the confusion! :) If I use the latest sysbox release (v0.6.1) without shiftfs, then will I hit any known issues or will I miss any features? Is there any performance impact related to this decision?
```
# uname -r
6.1.10-12.ph5-esx
```

**Comment by ctalledo** [comment]
Hi @shadjiiski,

> I am evaluating the option to use sysbox on [PhotonOS](https://vmware.github.io/photon/)

Thanks! I used to work at VMware BTW a few years ago (ESX vmkernel team) :) 

> The [design readme](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/design.md?plain=1#L109-L115) suggests that shiftfs is redundant for kernel >= 5.19 while the [install-package readme](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-package.md?plain=1#L204-L206) still recommends to install it on kernel > 5.12

Apologies for the confusion. Here's the short story: 

Just a few weeks ago, my thinking was:

kernel < 5.12: shiftfs required
kernel 5.12 -> 5.18: shiftfs not required but recommended (i.e., ID-mapping works in most but not all mounts)
kernel >= 5.19: shiftfs not required (i.e., ID-mapping works on all container mounts).

But then I realized that ID-mapping still does not work on `tmpfs` mounts into the container until kernel 6.1. And furthermore, even with that kernel, Sysbox needs a fix to apply ID-mapping on tmpfs in kernels >= 6.1.

With that in mind, my current thinking is:

kernel < 5.12: shiftfs required
kernel >= 5.12: shiftfs not required but recommended (i.e., ID-mapping works in most but not all mounts)

Once we update Sysbox to leverage ID-mapping on tmpfs, the requirement will be:

kernel < 5.12: shiftfs required
kernel 5.12 -> 6.0: shiftfs not required but recommended (i.e., ID-mapping works in most but not all mounts)
kernel >= 6.1: shiftfs not required (i.e., ID-mapping works on all container mounts).

Both the design guide and install-package docs need to be updated to this.

> If I use the latest sysbox release (v0.6.1) without shiftfs, then will I hit any known issues or will I miss any features? Is there any performance impact related to this decision?

Without shiftfs, then at a minimum you need kernel 5.12+. But the container setup will be faster in kernel 5.19+, since it brings support for ID-mapping of overlayfs. 

Hope that helps!

**Comment by shadjiiski** [comment]
Thanks for the detailed information! Then my understanding is I can play with photon 5 (kernel 6.1) without shiftfs unless I need tmpfs mounts. If I need them, I either need shiftfs or should wait for an updated sysbox.

That should be great for now. Do you guys have any rough ETA on when this Sysbox update might be released? I am trying to minimize the number of external components that I need to manage, so having all dependencies in the kernel itself sounds really tempting.

**Comment by ctalledo** [comment]
Hi @shadjiiski,

> Thanks for the detailed information! Then my understanding is I can play with photon 5 (kernel 6.1) without shiftfs unless I need tmpfs mounts. If I need them, I either need shiftfs or should wait for an updated sysbox.

Correct. 

> Do you guys have any rough ETA on when this Sysbox update might be released? I am trying to minimize the number of external components that I need to manage, so having all dependencies in the kernel itself sounds really tempting.

We should have a patch release in the next 2->3 weeks. I will make sure to include the tmpfs fix there. 

With kernel 6.1 plus the updated Sysbox you should be good to without shiftfs. Even without the updated Sysbox things will likely work mostly fine, except tmpfs mounts will show up with `nobody:nogroup` inside the Sysbox container, though they may still be writeable from within the container if they have "read-write-other" permissions.

**Comment by shadjiiski** [comment]
Thanks, I think this is all I needed here :)
