### ISSUE TITLE
pull private image inside sysbox container failed

### ISSUE THREAD

**Issue by yuanaisha** [nestybox/sysbox#731]
when i pulling our private image inside sysbox container, i‘m seeing the error:

```bash
root@k8sha-worker07:~# docker pull harbor.cngb.org/stereonote_hpc_external/heqiqi_6ef1d8bd107c4c8b8b782d6d0b7d36c2_private
Using default tag: latest
latest: Pulling from stereonote_hpc_external/heqiqi_6ef1d8bd107c4c8b8b782d6d0b7d36c2_private
2d473b07cdd5: Pulling fs layer
3ffda851a05c: Pulling fs layer
25e281dc4556: Pull complete
99976762f1a9: Pull complete
7fe8b23bdee3: Pull complete
56053361d62b: Pull complete
67cbf7f69783: Pull complete
7e4e086ce513: Extracting [==================================================>]  38.99MB/38.99MB
ffabbfdc0fed: Download complete
a6bbce5c53f9: Download complete
ac16e5b56c37: Download complete
9111a8a97450: Download complete
b22ba5e6e830: Download complete
e03dc54451c1: Download complete
1bbadf690e02: Download complete
a42650eb2b24: Download complete
f3cd720fed87: Download complete
20cd7d6e870e: Download complete
ee31f2b7df42: Download complete
7249ef27f7be: Download complete
d59f2cf27075: Download complete
83ed8adc04cc: Download complete
db5ea9afa164: Download complete
552596df8147: Download complete
5f72fb76ed38: Download complete
9380e3048abe: Download complete
3d5b397f8f38: Download complete
ffe51214e77c: Download complete
ed048d54a1c2: Download complete
a112dd4bfeaa: Download complete
143f9b2471cf: Download complete
6cdbf14889f5: Download complete
5c54c19ec205: Download complete
f6622964fd1c: Download complete
17c9fdb82783: Download complete
e7a59bb564c1: Download complete
ce34da8863ff: Download complete
ef357bddbfdf: Download complete
cb8f231a22e7: Download complete
ed65c56ca19e: Download complete
d74424995781: Download complete
94fdbdc79043: Download complete
66a7d71eba3f: Download complete
98505e1b2e30: Download complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/opt/lib" for UID 1001282, GID 2773 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /opt/lib: invalid argument
```

here is my  /etc/subuid and /etc/subgid:

```bash
root@k8sha-worker07:~# cat /etc/subuid
admin:100000:65536
root@k8sha-worker07:~# cat /etc/subgid
admin:100000:65536
```

then i changed /etc/subuid and /etc/subgid, restart the sysbox-mgr service ,restart sysbox container,but the error  is still there.

```bash
root@k8sha-worker07:~# cat /etc/subuid
admin:100000:5000000
root@k8sha-worker07:~# cat /etc/subgid
admin:100000:5000000
```

When we create private image, we copy some large uid files into the image, We have many such needs,because of the large number of files, changing the uid/gid of the files in advance will bring a lot of work,

Do you have any ideas? i saw this issue ,but it is closed[#443](https://github.com/nestybox/sysbox/issues/443)

Thank you!

**Comment by EddieX64** [comment]
Hello,

I'm having the same issue during pulling an image with large uid/gid inside: 
`failed to Lchown "/tmp/containerd-mount232417504/usr/local/bin/vctl" for UID 1672090608, GID 510800513: lchown /tmp/containerd-mount232417504/usr/local/bin/vctl: invalid argument.`

I have tried increasing uid/gid mapping in /etc/subuid and /etc/subgid inside of a sysbox pod, but it did not help. @ctalledo Forgive me for my lack of competency on this, but could you please explain why this is happening and are there any options to solve this problem? 

Thanks!

**Comment by EddieX64** [comment]
I have found a solution to this:

According to https://github.com/nestybox/sysbox/blob/master/docs/user-guide/security.md#userns-id-mapping-range
> By default, Sysbox reserves a range of 268435456 user IDs (enough to accommodate 4K system containers, each with 64K user IDs)

So, in my case, we have to pull private images with huge UID 1672090608, GID 510800513. I had to go to K8S worker nodes, manually update the content of `/etc/subuid` and `/etc/subgid` to something like this:
```
containers:100000:4000000000
sysbox:4000000000:65536
```
 After that i restarted the systemd sysbox and crio services and set the pod annotation `io.kubernetes.cri-o.userns-mode:auto:size=1672090609` which is enough for me to create 2 pods on one node, since we allocate to one pod two times less resources than there are on the node. And voila, I can pull and run the docker image with UID 1672090608 and GID 510800513. However, i would like to understand how to configure it during the sysbox daemonset installation on GKE cluster, because we have large amount of nodes that are scaled up and down during the week and it will be a nightmare to configure all of them manually. @ctalledo Is there a way to customize` /etc/subuid` and `/etc/subgid` contents during the sysbox daemonset installation somehow?

**Comment by EddieX64** [comment]
For someone who's looking for a possible solution to this:
I ended up modifying the sysbox-deploy-k8s daemonset including the init container that checks the `containers` user in `/etc/subuid` and `/etc/subgid` and adjust id range as needed. The `sysbox-deploy-k8s.sh` script executed in the daemonset already contain condition to not touch `/etc/subuid` and `/etc/subgid` if a large enough subid config already exists : https://github.com/nestybox/sysbox-pkgr/blob/master/k8s/scripts/sysbox-deploy-k8s.sh#L553-L554

**Comment by ctalledo** [comment]
Hi @EddieX64, apologies for the super-late reply.

> we have to pull private images with huge UID 1672090608, GID 510800513

Glad you were able to get past the problem, but it seems to me the crux of the problem is that the container image requires such a large UID range. Normally, in containers, the UIDs are in the range < 64K. So I would look into why that particular private image has a large UID range (it almost seems like a mistake).
