### ISSUE TITLE
Install sysbox without removing existing Docker containers

### ISSUE THREAD

**Issue by bluelul** [nestybox/sysbox#736]
To prevent running "docker rm $(docker ps -a -q) -f" while installing sysbox, I've added network config to /etc/docker/daemon.json (as [here](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-package.md#installing-sysbox-without-restarting-docker)). 
Then I run "sudo apt-get install ./sysbox-ce_0.6.1-0.linux_amd64.deb", but it still show error:
```
The Sysbox installer requires a docker service restart to configure network parameters, but it cannot proceed due to existing Docker containers. Please remove them as indicated below and re-launch the installation process. Refer to Sysbox installation documentation for details.
        "docker rm $(docker ps -a -q) -f"
```
I have a lot of container that can not be removed, backing up all of them to images is not a good way.
How can I install sysbox without removing existing Docker containers.
Thanks for help

**Comment by ctalledo** [comment]
Hi @bluelul, thanks for reaching out.

> How can I install sysbox without removing existing Docker containers.

I don't know if this is doable.

The Sysbox package installer [checks that no containers are running](https://github.com/nestybox/sysbox-pkgr/blob/25554c19b64288192bc28bacb573d8cc59e786cd/deb/sysbox-ce/sysbox-ce.config#L103) because it wants to restart Docker. And it wants to restart Docker because [it's adjusting the Docker Engine's network config](https://github.com/nestybox/sysbox-pkgr/blob/25554c19b64288192bc28bacb573d8cc59e786cd/deb/sysbox-ce/sysbox-ce.postinst#L188) to prevent overlapping IPs in the Docker container subnets between the outer Docker and a nested Docker Engine (since folks often use Sysbox for Docker-in-Docker).

You can always remove that check in the Sysbox packager code (links above) and rebuild the package by typing `make sysbox-ce <target-linux-distro>` in the sysbox-pkgr directory ([see Makefile here](https://github.com/nestybox/sysbox-pkgr/blob/master/Makefile)) and then install it as usual. But if you remove that check you'll likely face networking issues with the nested containers.

**Comment by bluelul** [comment]
Hi @ctalledo, thanks for your detailed reply.

After reading `sysbox-pkgr` in the links you provided, I've found that the `sysbox-ce.config` file uses `dockerCfgFile` variable without declaring it, not like `sysbox-ce.postinst` and `sysbox-ce.postrm`:
```bash
# Dockerd default configuration dir/file.
dockerCfgDir="/etc/docker"
dockerCfgFile="${dockerCfgDir}/daemon.json"
```

I think that's why the trick I mentioned earlier didn't work.

**Comment by systemofapwne** [comment]
> Hi @ctalledo, thanks for your detailed reply.
> 
> After reading `sysbox-pkgr` in the links you provided, I've found that the `sysbox-ce.config` file uses `dockerCfgFile` variable without declaring it, not like `sysbox-ce.postinst` and `sysbox-ce.postrm`:
> 
> ```shell
> # Dockerd default configuration dir/file.
> dockerCfgDir="/etc/docker"
> dockerCfgFile="${dockerCfgDir}/daemon.json"
> ```
> 
> I think that's why the trick I mentioned earlier didn't work.

Thank you for pointing this out. I had the same issue.
My workaround was setting this variable prior the installation process:

``dockerCfgFile=/etc/docker/daemon.json apt install ./sysbox-ce_0.6.2-0.linux_amd64.deb``

TBH, this has to be fixed in the package scripts.

**Comment by ctalledo** [comment]
Hi folks, thanks for reporting this the missing variable in sysbox-ce.config was just fixed via this PR: https://github.com/nestybox/sysbox-pkgr/pull/118

I guess we can close this ticket now?
